// frontend-user/src/views/Login/Login.vue
<script setup>
import store from '../../store';
</script>
<template>
  <div class="login">
    <a-row
        justify="center"
        type="flex"
    >
      <a-col>
        <img
            alt="网站主LOGO"
            :src="store.getters.config.logo"
            style="width: 300px;"
        >
      </a-col>
    </a-row>
    <a-row
        justify="center"
        style="padding-bottom:20px"
        type="flex"
    >
      <a-col>
        <h2 style="color:rgb(23, 7, 66)">
          {{ store.getters.config.title }}
        </h2>
      </a-col>
    </a-row>
    <a-row
        :gutter="[0,20]"
        align="middle"
        justify="start"
        type="flex"
    >
      <a-col span="8">
        <div style="text-align: right; padding-right: 10px">
          用户名
        </div>
      </a-col>
      <a-col span="8">
        <a-input
            v-model:value="username"
            placeholder="输入用户名"
        />
      </a-col>
      <a-col span="8"/>

      <a-col span="8">
        <div style="text-align: right; padding-right: 10px;">
          密码
        </div>
      </a-col>
      <a-col span="8">
        <a-input-password
            v-model:value="password"
            placeholder="输入密码"
        />
      </a-col>
      <a-col span="8"/>

      <a-col span="8"/>
      <a-col span="4">
        <a-button
            :disabled="username===''||password===''"
            shape="round"
            type="primary"
            @click="login"
        >
          登录
        </a-button>
      </a-col>
      <a-col span="4">
        <router-link to="./forget">
          忘记密码
        </router-link>
      </a-col>
    </a-row>

    <a-divider/>
    <a-row
        justify="center"
        style="padding-bottom:20px"
        type="flex"
    >
      <a-col span="4">
        <p> 没有账号？</p>
      </a-col>
      <a-col span="4">
        <router-link to="./register">
          注册
        </router-link>
      </a-col>
    </a-row>
  </div>
</template>

<script>
import axios     from 'axios';
import {message} from 'ant-design-vue';


export default {
  name: 'Login',
  data() {
    return {
      username: '',
      password: '',
    };
  },
  methods: {
    login() {
      axios.post('/v1/auth/login', {
        username: this.username,
        password: this.password,
      }).then((res) => {
        store.commit('userLogin', res.data.username);
        localStorage.setItem('token', res.data.token);
        message.success('登录成功');
        this.$router.push({name: 'Home'});
      });
    },
  },
};
</script>

<style scoped>
.login {
  background: white;
  width: 80%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  margin: 0 auto;
}
</style>

// frontend-admin/src/pages/Auth/Login/index.tsx
//+-------------------------------------------------------------------------
//
//  登录
//
//  File:       Login.tsx
//
//  Directory:  src/pages/Auth/Login
//
//  History:    Sep-08-2021   Charlie Chiang  Created
//
//--------------------------------------------------------------------------

import React, { FC, useState }                                 from 'react';
import {
  Button, Col, Form, Input, message, Row, Typography,
} from 'antd';
import { LockOutlined, UserOutlined }                          from '@ant-design/icons';
import http                                                    from 'utils/http';
import Typical                                                 from 'react-typical';
import './index.less';

const Login: FC = () => {
  const [isLoading, setLoading] = useState<boolean>(false);

  const handleLogin = (formData) => {
    console.log(formData);
    if (!formData.username || !formData.password) {
      message.error('请填写用户名与密码');
      return;
    }

    setLoading(true);
    http.post<{ username: string, token: string }>('/v1/auth/login', {
      username: formData.username,
      password: formData.password,
    })
      .then((res) => {
        localStorage.setItem('token', res.token);
        setTimeout(() => {
          setLoading(false);
          window.location.href = '/home';
        }, 500);
      })
      .catch((err) => {
        message.error(err);
        setTimeout(() => {
          setLoading(false);
        }, 1000);
      });
  };

  return (
    <div className="gradient-background login-root">
      <Row
        className="login-modal"
        align="middle"
        justify="center"
        gutter={[0, 12]}
      >
        <Col style={{ textAlign: 'center', marginTop: 36 }}>
          <img width={120} height={120} src="/logo.svg" alt="logo" />
          <Typography.Text
            style={{
              fontSize: 18, color: 'rgba(0,0,0,0.36)', display: 'block', marginTop: 16,
            }}
          >
            <Typical
              loop={Infinity}
              steps={[
                'Frogsoft CMS',
                2000,
                '蛙软内容管理系统',
                2000,
              ]}
            />
          </Typography.Text>
          <Typography.Title
            style={{ fontSize: 24, color: 'rgba(0,0,0,0.75)', marginBottom: 24 }}
          >
            管理员后台管理
          </Typography.Title>
        </Col>
        <Col style={{ width: 380 }}>
          <Form
            onFinish={handleLogin}
          >
            <Form.Item
              name="username"
              // 不使用 rules 是因为校验不通过时它会影响透明背景
            >
              <Input
                className="login-input"
                placeholder="用户名"
                size="large"
                prefix={<UserOutlined />}
              />
            </Form.Item>
            <Form.Item
              name="password"
            >
              <Input.Password
                className="login-input"
                placeholder="密码"
                size="large"
                prefix={<LockOutlined />}
                maxLength={18}
              />
            </Form.Item>
            <Form.Item wrapperCol={{ offset: 8, span: 8 }}>
              <Button
                className="login-button"
                type="primary"
                htmlType="submit"
                style={{ width: '100%', marginTop: 16 }}
                loading={isLoading}
              >
                登录
              </Button>
            </Form.Item>
            <Form.Item wrapperCol={{ span: 24 }}>
              <Typography.Text
                style={{
                  fontSize: 12, color: 'rgba(0,0,0,0.36)', display: 'block', textAlign: 'center',
                }}
              >
                {`Frogsoft ${(new Date()).getFullYear()}. All Rights Reserved.`}
              </Typography.Text>
            </Form.Item>
          </Form>
        </Col>
      </Row>
    </div>

  );
};

export default Login;
